In [4]:
import pandas as pd
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np
#from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

# Import Data

In [3]:
#datasets = pd.read_excel('Universal_bank_dataset.xls',engine='openpyxl',sheet_name=1)
datasets = pd.read_csv('Universal_bank_dataset.csv')
datasets.drop(['ID','ZIP Code'],axis=1,inplace=True)

In [6]:
new_customer = pd.read_csv('Universal_bank_new.csv')
new_customer.drop(['Personal Loan'],axis=1,inplace=True)
new_customer

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,40,10,84,2,2,2,0,0,0,1,1

In [7]:
y_df = datasets[['Personal Loan']]
datasets.drop(['Personal Loan'],axis=1,inplace=True)
X_df = datasets
with pd.option_context('display.max_rows', 8): display(X_df)

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,1,0,0,0
1,45,19,34,3,1.5,1,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4996,30,4,15,4,0.4,1,85,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,1,1

In [8]:
X = X_df.values
y = y_df.values

# Preprocess

In [9]:
scaler = StandardScaler()
X_norm = scaler.fit_transform(X)
new = new_customer.values
new = scaler.transform(new)

# K-NN k=5

In [10]:
neigh = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
neigh.fit(X_norm, y)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(metric='euclidean')

In [11]:
y_pred = neigh.predict(new)
print(y_pred)

[0]

# Find Best k K-NN

In [12]:
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=0.6,random_state=1992)

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
scores = []
for k in range(1,21):
    neigh = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    neigh.fit(X_train, y_train.ravel())
    scores.append([k,neigh.score(X_test,y_test)])

In [ ]:
scores

[[1, 0.956],
 [2, 0.95],
 [3, 0.9575],
 [4, 0.9505],
 [5, 0.955],
 [6, 0.951],
 [7, 0.9555],
 [8, 0.951],
 [9, 0.9545],
 [10, 0.946],
 [11, 0.95],
 [12, 0.9445],
 [13, 0.9495],
 [14, 0.945],
 [15, 0.9485],
 [16, 0.944],
 [17, 0.9455],
 [18, 0.9425],
 [19, 0.946],
 [20, 0.941]]

In [ ]:
scores.sort(key=lambda x: x[1], reverse=True)
print(f"Best k={scores[0][0]} with accuracy score:{scores[0][1]}")

Best k=3 with accuracy score:0.9575

# Using Best k & Show Confusion Matrix

In [15]:
k = scores[0][0]
neigh = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
neigh.fit(X_train, y_train.ravel())

KNeighborsClassifier(metric='euclidean', n_neighbors=1)

In [16]:
y_pred = neigh.predict(X_test)
cm = confusion_matrix(y_test, y_pred) 
print(cm)
print(classification_report(y_test,y_pred))

[[1777   26]
 [  62  135]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1803
           1       0.84      0.69      0.75       197

    accuracy                           0.96      2000
   macro avg       0.90      0.84      0.87      2000
weighted avg       0.95      0.96      0.95      2000

In [17]:
y_pred = neigh.predict(new)
print(y_pred)

[0]