In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler

df = pd.read_excel(r'height_age_weight.xlsx')
with pd.option_context('display.max_rows', 10): display(df)

scaler = StandardScaler()

x = df[['height', 'age']]
x = scaler.fit_transform(x)
y = df['weight']

k = 3
model = KNeighborsRegressor(n_neighbors=k)
model.fit(x, y)

x_pred = [[170, 40]]
x_pred_sc = scaler.transform(x_pred)
y_pred = model.predict(x_pred_sc)

h = x_pred[0][0]
a = x_pred[0][1]
w = '{:.2f}'.format(y_pred[0])

print('K =', k)
print(f'Height: {h}, Age: {a} => Weight: {w}')
print('Accuracy:', '{:.2f}'.format(model.score(x, y)))

   height  age  weight
0  150.00   45      77
1  155.75   26      47
2  170.68   30      55
3  179.83   34      59
4  146.30   40      72
5  176.78   36      60
6  161.54   19      40
7  176.78   28      60
8  167.64   23      45
9  170.68   32      58

K = 3
Height: 170, Age: 40 => Weight: 59.00
Accuracy: 0.87

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(